### ISSUE TITLE
arg.method

### ISSUE THREAD

**Issue by tomorrow05** [RobinLu1209/Geometer#1]
Hello, I want to know what **arg.method** is. Thank you very much for your reply.
![image](https://user-images.githubusercontent.com/72803141/184522467-23f5ee56-9263-464a-9f72-199216ebe1ee.png)

**Comment by RobinLu1209** [comment]
Sorry for this error. This is a parameter left over from the historical version. In the current version, this parameter is not required and can be deleted directly. We will also modify this error in the code as soon as possible. Thank you for your attention to our work.
